
JBoss Seam - Contextual Component framework for Java EE
-------------------------------------------------------
This software is distributed under the terms of the FSF Lesser Gnu
Public License (see link:distribution/src/main/assembly/lgpl.txt[]). 

Seam 2: Next generation enterprise Java development
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Seam 2.3 targets Java EE 6 capabilities such as JSF2 and JPA2 on the JBoss Enterprise Application Platform 6 (JBoss AS 7) - Seam 2.3 also supports RichFaces 4 which is also available for commercial support via Web Framework Kit. If you are looking for the long-term support with a service level agreement of Seam 2.2 and/or Seam 2.3 then please contact us at http://www.redhat.com/contact/sales.html - Seam 2.3 is part of Web Framework Kit, included as part of the JBoss Enterprise Application Platform subscription.

Seam 2.3 was released in September 2012. This is an update to the Seam 2 code base to make it compatible with Jave EE 6.

Seam 2 is a powerful open source development platform for building rich Internet applications in Java. Seam integrates technologies such as Asynchronous JavaScript and XML (AJAX), JavaServer Faces (JSF), Java Persistence (JPA), Enterprise Java Beans (EJB 3.1) and Business Process Management (BPM) into a unified full-stack solution, complete with sophisticated tooling.

Seam has been designed from the ground up to eliminate complexity at both architecture and API levels. It enables developers to assemble complex web applications using simple annotated Java classes, a rich set of UI components, and very little XML. Seam's unique support for conversations and declarative state management can introduce a more sophisticated user experience while at the same time eliminating common bugs found in traditional web applications. 

Learn more
~~~~~~~~~~
* Read the documentation in the link:seam-reference-guide/src/docbook/en-US[reference documentation] directory
* Read the online FAQ http://www.seamframework.org/Documentation/FAQs


Notes for this release
~~~~~~~~~~~~~~~~~~~~~~
Be warned that JBoss Embedded is *LEGACY runtime* and is not in Seam 2.3 distribution *anymore*


Wildfly Support
~~~~~~~~~~~~~~~
This link:https://github.com/mark1900/jboss-seam/tree/seam_2_3-wildfly_10_1_0_Final[branch] attempts to update Seam 2.3 to support JEE 7, JSF 2.2, Servlet 3.1, RESTEasy 3.0.19 and run properly on Wildfly 10.1.0.Final.

This link:https://github.com/mark1900/jboss-seam/tree/seam_2_3-wildfly_10_1_0_Final[branch] also depends on a customized release of link:https://github.com/mark1900/jbpm3-seam/tree/3.2.10.SP3_seam2_hibernate5[jbpm3] and link:https://github.com/mark1900/jbpm3-seam/tree/3.2.10.SP3_seam2_hibernate5/projects/jsf-console-3.2.10-seam[jsf-console].


*Building and Releasing the Components*

* *jbpm3-seam* - https://github.com/mark1900/jbpm3-seam/tree/3.2.10.SP3_seam2_hibernate5

[source,shell]
----

#!/bin/bash
set -e
set -x
 
id
 
JBPM_VERSION_FROM=3.2.10-1-SP3_seam2_hibernate5-SNAPSHOT
JBPM_VERSION_TO=3.2.10-1-SP3_seam2_hibernate5
 
 
rm -rf ${WORKSPACE}/github
mkdir ${WORKSPACE}/github
cd ${WORKSPACE}/github
 
git clone -b 3.2.10.SP3_seam2_hibernate5 https://github.com/mark1900/jbpm3-seam.git
zip -r jbpm3-seam-3.2.10.SP3_seam2_hibernate5.zip jbpm3-seam
find ${WORKSPACE}/github/jbpm3-seam -type f -name "pom.xml" -exec sed -i "s/${JBPM_VERSION_FROM}/${JBPM_VERSION_TO}/g" {} \;
 
 
# Maven Command
mvn -B -f ${WORKSPACE}/github/jbpm3-seam/pom.xml -U -P prod -X -e clean help:effective-settings help:effective-pom install -DskipTests=true
----

* *jsf-console* - https://github.com/mark1900/jbpm3-seam/tree/3.2.10.SP3_seam2_hibernate5/projects/jsf-console-3.2.10-seam

[source,shell]
----

#!/bin/bash
set -e
set -x
 
id
 
JBPM_VERSION_FROM=3.2.10-1-SP3_seam2_hibernate5-SNAPSHOT
JBPM_VERSION_TO=3.2.10-1-SP3_seam2_hibernate5
JSF_CONSOLE_VERSION_FROM=3.2.10-1-seam2_hibernate5-SNAPSHOT
JSF_CONSOLE_VERSION_TO=3.2.10-1-seam2_hibernate5
 
 
rm -rf ${WORKSPACE}/github
mkdir ${WORKSPACE}/github
cd ${WORKSPACE}/github
 
git clone -b 3.2.10.SP3_seam2_hibernate5 https://github.com/mark1900/jbpm3-seam.git
zip -r jsf-console-3.2.10-1-seam2_hibernate5.zip jbpm3-seam/projects/jsf-console-3.2.10-seam
find ${WORKSPACE}/github/jbpm3-seam -type f -name "pom.xml" -exec sed -i "s/${JBPM_VERSION_FROM}/${JBPM_VERSION_TO}/g" {} \;
find ${WORKSPACE}/github/jbpm3-seam -type f -name "pom.xml" -exec sed -i "s/${JSF_CONSOLE_VERSION_FROM}/${JSF_CONSOLE_VERSION_TO}/g" {} \;
 
# Maven Command
mvn -B -f ${WORKSPACE}/github/jbpm3-seam/projects/jsf-console-3.2.10-seam/pom.xml -U -P prod -X -e clean help:effective-settings help:effective-pom install

----

* *jboss-seam* - https://github.com/mark1900/jboss-seam/tree/seam_2_3-wildfly_10_1_0_Final

[source,shell]
----

#!/bin/bash
set -e
set -x
 
id
 
SEAM_VERSION_FROM=2.3.2-1-wildfly_10_1_0_Final-SNAPSHOT
SEAM_VERSION_TO=2.3.2-1-wildfly_10_1_0_Final
JBPM_VERSION_FROM=3.2.10-1-SP3_seam2_hibernate5-SNAPSHOT
JBPM_VERSION_TO=3.2.10-1-SP3_seam2_hibernate5

 
rm -rf ${WORKSPACE}/github
mkdir ${WORKSPACE}/github
cd ${WORKSPACE}/github
 
git clone -b seam_2_3-wildfly_10_1_0_Final https://github.com/mark1900/jboss-seam.git
zip -r jboss-seam-seam_2_3-wildfly_10_1_0_Final.zip jboss-seam
find ${WORKSPACE}/github/jboss-seam -type f -name "pom.xml" -exec sed -i "s/${SEAM_VERSION_FROM}/${SEAM_VERSION_TO}/g" {} \;
find ${WORKSPACE}/github/jboss-seam -type f -name "pom.xml" -exec sed -i "s/${JBPM_VERSION_FROM}/${JBPM_VERSION_TO}/g" {} \;
 
 
# Maven Command
mvn -B -f ${WORKSPACE}/github/jboss-seam/pom.xml -U -P prod -X -e clean help:effective-settings help:effective-pom install

----
